apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: go-hap
spec:
  maxReplicas: 6
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: go-hpa
  targetCPUUtilizationPercentage: 15